### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by WaLkZa** [shosatojp/google-slide-dl#1]
I'm trying with
```python3 google-slide-dl.py https://docs.google.com/presentation/d/e/2PACX-1vSUStwkhVvm0ddmTPqfyUF1Fpg82FT4v0uqnIZYW5ntiqAw4tDIu_sUyNafts-hLwPBKPfHQJLKu6wU/pub```
but i got error
```C:\Users\Simeon Nikolov\Desktop\google-slide-dl>python3 google-slide-dl.py https://docs.google.com/presentation/d/e/2PACX-1vSUStwkhVvm0ddmTPqfyUF1Fpg82FT4v0uqnIZYW5ntiqAw4tDIu_sUyNafts-hLwPBKPfHQJLKu6wU/pub
Traceback (most recent call last):
  File "C:\Users\Simeon Nikolov\Desktop\google-slide-dl\google-slide-dl.py", line 19, in <module>
    os.makedirs(args.dir)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType```


What i'm doing wrong?

**Comment by shosatojp** [comment]
Thank you for reporting.

## Why this error occurrred?

A bug which `--dir` option wasn't set as "required".

## How I fixed it?

I have fixed this bug by using slide title as output directory if `--dir` option is not provided in this [commit](https://github.com/shosatojp/google-slide-dl/commit/2d1f921d41237074114d88e58ece7dc7f08eddfd).

```sh
# slide title is used as output directory
python3 google-slide-dl.py 'https://docs.google.com/presentation/d/e/.../pub'

# or use provided directory
python3 google-slide-dl.py --dir your_output_dir 'https://docs.google.com/presentation/d/e/.../pub'
```

This should be work fine at latest master branch.
